name: simple_nvr
description: simple NVR
url: https://github.com/augin/simple_nvr
image: augin/simple_nvr
arch: [ amd64, aarch64, i386, armv7 ]

# https://developers.home-assistant.io/docs/add-ons/configuration
version: 1.8.2
slug: simple_nvr
init: false
startup: system
host_network: true
homeassistant_api: true
video: true
audio: true
ingress: true
ingress_port: 8180
panel_icon: mdi:file-video
panel_title: Записи видеокамер
panel_admin: false
map: 
  - config:rw
  - media
  - ssl
  - share:rw
